version: "3.8"

services:
  server:
    build: ./server
    command: npm run dev
    ports:
      - '3001:${PORT}'
    env_file:
      - .env.development
    volumes:
      - ./server:/home/node/app
    depends_on:
      - db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=db
      
  db:
    image: "postgres:13"
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env.development
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
